[package]
name = "plutocraft"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.5.0-rc.1"
lazy_static = "1.4.0"
simple-logging = "2.0.2"
log = "0.4.14"
chrono = "0.4.19"